---
- name: Grant REPLICATION CLIENT and PROCESS on all DBs and SELECT on performance_schema DB for datadog user
  mysql_user:
    name: 'datadog'
    password: "{{ datadog_mysql_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT/performance_schema.*:SELECT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ db_ip }}"
    append_privs: yes
  become: yes
  notify:
    - Restart mysql service
    - Restart datadog-agent service

- name: Add mysql integration to datadog-agent config files
  template:
    src: mysql.yaml.j2
    dest: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
  become: yes
  notify:
    - Restart datadog-agent service