---
- name: Install httpd for redhat systems
  yum:
    name: "httpd"
    state: present
- name: Start the httpd service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
- name: Open port 80
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: yes
  when: ansible_virtualization_type != 'docker'
- name: Restart the firewalld service
  service:
    name: firewalld
    state: restarted
  become: yes