- name: Install httpd
  yum:
    name: "httpd"
    state: present
- name: Start the httpd service
  service:
    name: httpd
    state: started
    enable: yes
  become: yes
#- name: Open port 80
#  firewalld:
#    service: http
#    permanent: true
#    state: enabled
- name: Restart the firewalld service
  service:
    name: firewalld
    state: restarted