- name: Install httpd
  yum:
    name: "httpd"
    state: present
- name: Start the httpd service
  service:
    name: httpd
    state: started
- name: Open port 80
  firewalld:
    service: http
    permanent: true
    state: enabled
- name: Start the firewalld service
  service:
    name: firewalld
    state: restarted