---
- name: Install httpd for redhat systems
  yum:
    name: "httpd"
    state: present
- name: Start the httpd service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
- name: Open http & https ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  become: yes
  with_items:
    - "http"
    - "https"
  notify:
    - Restart firewalld service
  when: ansible_virtualization_type != 'docker'