---
- name: Run os specific dependencies for docker-ce installation
  import_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'
- import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'
- import_tasks: archlinux.yml
  when: ansible_os_family|lower == 'archlinux'

- name: Enable & start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
