---
- name: Run os specific dependencies for docker-ce installation
  import_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'
- import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'
- import_tasks: archlinux.yml
  when: ansible_os_family|lower == 'archlinux'

- name: Ensure docker group exists
  group:
    name: docker
    state: present
  become: yes

- name: Set docker group as owner of docker socket
  file:
    path: /var/run/docker.sock
    owner: root
    group: docker
  become: yes

- name: Enable & start docker service
  service:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes
