---
- name: Ensure PIAKUR_DEST_DIR dir exists
  file:
    path: "{{ PIKAUR_DEST_DIR }}"
    state: directory
  become: yes

- name: "Clone pikaur repository to PIKAUR_DEST_DIR"
  git:
    repo: "{{ REPO_URL }}"
    dest: "{{ PIKAUR_DEST_DIR }}/pikaur"
    version: master
  become: yes

- name: Ensure pyalpm is installed
  pacman:
    name: pyalpm
  become: yes

- name: Create symbolic link to path
  file:
    src: "{{ PIKAUR_DEST_DIR }}/pikaur/{{ PIKAUR_EXEC }}"
    dest: "{{ SYMLINK_DEST }}"
    state: link
  become: yes
