---
- name: Ensure /opt dir exists
  file:
    path: /opt
    state: directory
  become: yes

- name: "Clone pikaur repository to /opt"
  git:
    repo: https://github.com/actionless/pikaur
    dest: /opt/pikaur
    version: master
  become: yes

- name: Ensure pyalpm is installed
  pacman:
    name: pyalpm
  become: yes

- name: Create symbolic link to dotfiles
  file:
    src: /opt/pikaur/pikaur.py
    dest: /usr/bin/pikaur
    state: link
  become: yes
