---
- name: Install mysql repo on redhat systems
  become: true
  yum:
    name: "{{ item }}"
  with_items:
    - http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

- name: Install MySQL & MySQL-python on redhat systems
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server
    - MySQL-python
  become: yes