---
- name: Install php5 basic packages for debian systems
  action: >
    apt name={{ item }} state=present update_cache=yes
  with_items:
    - php5
    - php5-gd
    - php5-mysql
    - libapache2-mod-php5
    - php5-mcrypt
  become: yes
  when: ansible_os_family|lower == 'debian'

- name: Install php5 for redhat systems
  action: >
    yum name={{ item }} state=present update_cache=yes
  with_items:
    - php
    - php-mysql
    - php-mcrypt
  become: yes
  when: ansible_os_family|lower == 'redhat'

- name: Install php5 for arch systems
  action: >
    pacman name={{ item }} state=present update_cache=yes
  with_items:
    - php53
    - php53-mcrypt
    - php-ssh
    - php53-gd
  become: yes
  when: ansible_os_family|lower == 'archlinux'