---
- name: Install php5 basic packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - php5
    - php5-mysql
    - libapache2-mod-php5
    - php5-mcrypt
  become: yes