---
- name: "Ensure linux-image-extra is installed on ubuntu trusty systems"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - linux-image-extra-$(uname -r)
    - linux-image-extra-virtual
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
- name: "Ensure docker is installed"
  action: >
    {{ ansible_pkg_mgr }} name=docker state=present update_cache=yes
  become: yes
- name: Start docker service
  service:
    name: docker
    state: started
  become: yes