---
- hosts: localhost
  vars:
    container_name: nginx
  tasks:
  - name: Docker pull nginx
    docker_image:
      name: nginx
  - name: Start jenkins container
    docker_container:
      name: "{{ container_name }}"
      image: nginx
      ports:
        - "80:80"
  - name: Add {{ container_name }} container to in-memory inventory
    add_host:
      name: "{{ container_name }}"
      ansible_connection: docker
      groups: containers
