---
- hosts: localhost
  vars:
    container_name: centos
  tasks:
  - name: Docker pull {{ container_name }}
    docker_image:
      name: centos/python-35-centos7
  - name: Start {{ container_name }} container
    docker_container:
      name: "{{ container_name }}"
      image: centos/python-35-centos7
      command: sleep infinity
  - name: Add {{ container_name }} container to in-memory inventory
    add_host:
      name: "{{ container_name }}"
      ansible_connection: docker
      groups: containers
