---
- name: "Check if {{ wp_dl_path }} already exists"
  stat:
    path: "{{ wp_dl_path }}"
  register: stat_result

- name: "Download wordpress at {{ wp_dl_link }} to {{ wp_dl_path }}"
  get_url:
    url: "{{ wp_dl_link }}"
    dest: "{{ wp_dl_path }}"
    validate_certs: no
    mode: 0440
  when: stat_result.stat.exists == False

- name: "Extract {{ wp_dl_path }} to {{ wp_path }}"
  unarchive:
    src: "{{ wp_dl_path }}"
    dest: "{{ wp_path }}"
    remote_src: yes
  become: yes

- name: "Check if wordpress is present in {{ wp_path }}"
  stat:
    path: "{{ wp_path }}"
  register: stat_result

- name: Ensure php5-gd, libssh2-php and python-mysqldb are installed on debian systems
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=present
  with_items:
    - php7.0-gd
    - php-ssh2
    - python-mysqldb
  become: yes
  notify:
    - Restart apache service
  when: ansible_os_family == 'Debian'

- name: Ensure php-gd, php-ssh2 and MySQL-python are installed on redhat systems
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=present
  with_items:
    - php-gd
    - php-ssh2
    - MySQL-python
  become: yes
  notify:
    - Restart apache service
  when: ansible_os_family == 'RedHat'

- name: Create mysql wordpress database
  mysql_db:
    name: "{{ wp_mysql_db }}"
    state: present
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Create mysql wordpress user
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: "*.*:ALL"
    state: present
    login_password: "{{ mysql_root_password }}"
  become: yes
  notify:
    - Restart mysql service

- name: Export wp-config.php template
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
  become: yes